### ISSUE TITLE
Error when using plugin

### ISSUE THREAD

**Issue by andrehp** [larshesel/vmq_elixir_plugin#1] opened 2016-01-13 20:26 UTC
Hello,

I'm trying to use vmq_elixir_plugin, I followed the steps presented at the Readme, installing first vmq_elixir and then vmq_elixir_plugin, but even when using the default code the plugin does not work properly.

When running with the default code the following error happens:

2016-01-13 17:59:20.461 [error] <0.454.0> CRASH REPORT Process <0.454.0> with 0 neighbours exited with reason: call to undefined function elixir:start(normal, []) in application_master:init/4 line 133

And when a client connect to VerneMQ the following error happens:

2016-01-13 18:12:07.204 [error] <0.846.0> CRASH REPORT Process <0.846.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.Logger':bare_log(info, <<"{:auth_on_subscribe, :undefined, {[], \"mosquitto\"}, [{[\"rooms\", \"1\"], 1}]}">>, [{application,vmq_elixir_plugin},{module,'Elixir.VmqElixirPlugin'},{function,<<"auth_on_subscribe/...">>},...])

I'm just beginning to work with Elixir and I have no clue on how to solve this, any hints?

Thanks

**Comment by larshesel** [comment] 2016-01-13 20:34
Hi there - I'll take a closer look at this tomorrow morning, but maybe you can let me know which versions of Erlang and Elixir you're using?

**Comment by andrehp** [comment] 2016-01-13 20:55
Thanks!

Erlang:
Erlang/OTP 17 [erts-6.4] [source] [64-bit]

Elixir:
Elixir 1.0.4

I'm using Mac OS X El Capitan

**Comment by larshesel** [comment] 2016-01-14 06:47
I can reproduce the issue with the default code and will investigate. Thanks for reporting.

**Comment by andrehp** [comment] 2016-02-04 21:40
Ok, I kind of found a way of using Elixir in VerneMQ, though it is still probably not the best way.

So, to fix elixir crashing when starting I used rebar3 to compile vmq_elixir instead of rebar. But then I still wasn't able to use any external lib for Elixir. To fix this problem I had to add the paths of the .apps used by my plugin.

So in my case I added to vmq_elixir_app:

``` erlang
add_dirs_to_path(BasePath) ->
    error_logger:info_msg("Base path: ~p", [BasePath]),
    Dirs =
        %% If built with rebar3:
        filelib:wildcard(BasePath ++ "/../*/ebin"),
    error_logger:info_msg("Dirs: ~p", [Dirs]),
    case Dirs of
        [] ->
            {error, elixir_not_found};
        _ ->
            [code:add_patha(Dir) || Dir <- Dirs],
            ok
    end.
```

Where BasePath is the base path of the elixir plugin. It seems to be working, but more experimenting is still required.

I hope this can help other people trying to use Elixir with VerneMQ.

**Comment by larshesel** [comment] 2016-02-05 06:48
Hi

Thanks for getting back with this feedback and I apologize for not having moved forward with this. I'll try hard to see if I can spare a couple of hours during the next couple of days to get this back into a working state.

**Comment by larshesel** [comment] 2016-02-05 21:16
Hi again

I've just pushed a fix to this repo and `vmq_elixir`. The root cause seemed to be that I'd fixed the Elixir version loaded by `vmq_elixir` to version 1.0.4, but the plugin would be compiled with any release matching `~> 1.0` which includes the 1.1.x series which introduced and uses the function `Logger.bare_log/2`. This meant the plugin would be compiled for 1.1.x, but the available Elixir version in the VerneMQ erlang VM was 1.0.4 and thus not compatible with the plugin.

I've pinned both repos to 1.1.1 for now, but I think in general I need to find a better way to handle this situation. Let me know if it works (or not) if you try it out.

**Comment by andrehp** [comment] 2016-02-05 21:47
Hi,

Your push seems to fix the log error (by the way, where is the default directory for the log? I was only able to find the Erlang log output).

But the problem of loading other applications persists. A simple example is trying to use httpoison on my Elixir plugin, when I try to activate it VerneMQ gives the following error:

```
RPC to 'VerneMQ@127.0.0.1' failed: {'EXIT',
                                    {{{badmatch,
                                       {error,
                                        {httpoison,
                                         {"no such file or directory",
                                          "httpoison.app"}}}},
                                      ...
```

And to fix this I used the workaround I mentioned earlier, adding the .apps required by my application by hand. Though I wasn't able to think of a way to programatically add the dependencies required by the plugin.

**Comment by larshesel** [comment] 2016-02-06 15:15
Sorry, I hadn't understood the other issue you had, unfortunately.

That problem is due to the nature of VerneMQ plugins at the moment. A plugin is an otp-application and when enabling a plugin VerneMQ only loads the beam files for that particular plugin and not the beam files for any of the apps it depends on.

What you can do to workaround this for now is to load the httpoison app like any other plugin which will load the beam files into the erlang VM.

**Comment by larshesel** [comment] 2016-04-15 14:29
Since there's been no activity on this issue for a while I'm closing it. If you're still having issues, feel free to reopen.

**Closed as completed by larshesel** 2016-04-15 14:29 UTC
